In [1]:
### Libraries USed Tensorflow> 2.0  and keras


In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [16]:
### Vocabulary size
voc_size=10000

# One hot representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[5711, 1974, 1505, 3428], [5711, 1974, 1505, 9964], [5711, 3923, 1505, 3227], [2653, 4325, 7020, 1036, 1640], [2653, 4325, 7020, 1036, 1284], [9832, 5711, 1118, 1505, 8654], [26, 9565, 4945, 1036]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5711 1974 1505 3428]
 [   0    0    0    0 5711 1974 1505 9964]
 [   0    0    0    0 5711 3923 1505 3227]
 [   0    0    0 2653 4325 7020 1036 1640]
 [   0    0    0 2653 4325 7020 1036 1284]
 [   0    0    0 9832 5711 1118 1505 8654]
 [   0    0    0    0   26 9565 4945 1036]]


In [10]:
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
print(model.predict(embedded_docs))

[[[-1.0270812e-02 -2.3188436e-02  4.7448073e-02 -2.4022782e-02
   -5.7977811e-03  8.9616701e-04  3.9852370e-02 -4.6440255e-02
    4.9538020e-02 -1.1731863e-02]
  [-1.0270812e-02 -2.3188436e-02  4.7448073e-02 -2.4022782e-02
   -5.7977811e-03  8.9616701e-04  3.9852370e-02 -4.6440255e-02
    4.9538020e-02 -1.1731863e-02]
  [-1.0270812e-02 -2.3188436e-02  4.7448073e-02 -2.4022782e-02
   -5.7977811e-03  8.9616701e-04  3.9852370e-02 -4.6440255e-02
    4.9538020e-02 -1.1731863e-02]
  [-1.0270812e-02 -2.3188436e-02  4.7448073e-02 -2.4022782e-02
   -5.7977811e-03  8.9616701e-04  3.9852370e-02 -4.6440255e-02
    4.9538020e-02 -1.1731863e-02]
  [-3.0972445e-02  3.6916327e-02  4.4505682e-02  3.6603544e-02
   -9.9383108e-03 -1.4217719e-03 -3.7907410e-02 -2.1881580e-02
    4.2002749e-02 -9.0598464e-03]
  [-2.1518100e-02 -2.8569214e-03 -1.4314540e-03 -3.3308409e-02
    6.2389001e-03  2.0910155e-02  2.2283707e-02  4.0981974e-02
    2.5211465e-02  4.4119570e-02]
  [-4.3500114e-02  1.7475057e-02  3.6210

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5711, 1974, 1505, 3428])

In [15]:
print(model.predict(embedded_docs)[0])

[[ 0.02483806 -0.0322034  -0.02573475 -0.02727897 -0.00883416  0.02790247
  -0.0202525   0.03295917 -0.03288496  0.01991537]
 [ 0.02483806 -0.0322034  -0.02573475 -0.02727897 -0.00883416  0.02790247
  -0.0202525   0.03295917 -0.03288496  0.01991537]
 [ 0.02483806 -0.0322034  -0.02573475 -0.02727897 -0.00883416  0.02790247
  -0.0202525   0.03295917 -0.03288496  0.01991537]
 [ 0.02483806 -0.0322034  -0.02573475 -0.02727897 -0.00883416  0.02790247
  -0.0202525   0.03295917 -0.03288496  0.01991537]
 [-0.04887073  0.0051278   0.02714482  0.03193164 -0.013307   -0.02486857
   0.00245196  0.04782417 -0.00122316 -0.01849063]
 [-0.02832967  0.04099344  0.04662745 -0.01869171 -0.03927068 -0.03918898
  -0.00371127 -0.02290197 -0.00174804 -0.02809923]
 [ 0.04426736 -0.00058271  0.04821532  0.02951224 -0.03881714  0.04021147
   0.01224152 -0.00932059  0.04396078 -0.01037068]
 [ 0.0328573  -0.03427432 -0.04881542 -0.02700875  0.03868062  0.04876507
   0.02406463 -0.0266125  -0.04575327 -0.03264005]]